### ISSUE TITLE
Neckro forced 'store' timer/counter

### ISSUE THREAD

**Issue by Kherae** [jpw1991/chebs-necromancy#128]
while the implementation of "deposit if nothing to pick up" is good, there's still one case that could use some attention: continuous slow production that does not fill the neckro's inventory very quickly.
Thus, my suggestion: have a configuration option to make the neckro deposit after a specific amount of time.

**Comment by CW-Jesse** [comment]
"Minimum time between deposits"?

**Comment by Kherae** [comment]
more like "maximum time between deposits"

**Comment by jpw1991** [comment]
Sounds good to me. The way I typically do this is to store the value of `Time.time` and then compare against that in the update loop. Check the code for [Guardian Wraith expiring after X seconds](https://github.com/jpw1991/chebs-necromancy/blob/master/ChebsNecromancy/Minions/GuardianWraithMinion.cs#L34).

Why not use a coroutine? Because I've found that coroutines can misbehave on creatures for some reason. It works great for static structures that don't move around, like pylons, but somehow malfunctions for creatures.

**Comment by CW-Jesse** [comment]
All right. The timer should probably only start once it picks up the first object.

**Comment by jpw1991** [comment]
@CW-Jesse you want this one?

**Comment by jpw1991** [comment]
This is now working in 2.3.10. You can test this [here](https://github.com/jpw1991/chebs-necromancy/pull/148) if you wish. Attention: assumes newest Valhiem version + upgraded BepInEx and Jotunn
