### ISSUE TITLE
WardisLove incompatibility with non-commandable summons (necros, lumberjacks, etc)

### ISSUE THREAD

**Issue by Zudakas** [jpw1991/chebs-necromancy#177]
# Describe the bug
Incompatibility with WardIsLove mod - Push Creatures out of ward area setting. If turned on, all non-commandable summons (Neckros, Lumberjacks, Miners, etc) will be pushed from the ward area, including through walls. If creature damage is turned on, they are also damaged.

# To Reproduce (if applicable)
Install WardIsLove mod ( https://valheim.thunderstore.io/package/Azumatt/WardIsLove/ ) and turn on Push Creatures from Ward Area, as well as Damage Creatures within Ward Area.

Summon non-commandable summons, or place summoning pylons for Neckros (Not sure about the bats, leeches, or the others, but assumably they are also affected).

# Expected behavior (if applicable)
Summons behave as intended, unaffected by the ward (

# Screenshots (if applicable)

# Desktop
 - OS: Windows 10
 - Mod version 2.5.11
 - Game version Current (Mistlands Update)
 
 #Possible Fix:
Apply tameable tag to all summons if possible.

**Comment by jpw1991** [comment]
Hi Zudakas,

Thanks for opening the issue. Unfortunately, I cannot apply Tameable to the Neckros and Worker minions because, especially in the case of the Neckro, it will mess up their functionality.

## Possible Solutions

### Faction check

Azumatt checks not only `Tameable` but also the creature's faction because the minions belong to the `Player` faction - even if they have no `Tameable` component on them.

### Exceptions List

Maybe certain creatures can be exempted via configs and won't be affected by the ward. Something like `Exemptions = ChebGonaz_NeckroGatherer,ChebGonaz_SkeletonWoodcutter,ChebGonaz_SkeletonMiner`

**Comment by Zudakas** [comment]
Ok, wasn't sure if it was an easy fix on your end or not, I'll go pester them :)

**Comment by jpw1991** [comment]
Sounds good haha. You can point them here and I'll help, if I can, to solve the problem

**Comment by jpw1991** [comment]
As of the newest version, only the Neckro should be affected by the ward. The workers count as tames
