### ISSUE TITLE
Can't control woodcutter skeletons

### ISSUE THREAD

**Issue by Mirakakel** [jpw1991/chebs-necromancy#220]
By default they spawn always roaming, therefore destroying any wood in their sight, and i can't stop them.
Can't make them follow me, can't command them to wait.
Skeleton warriors are working as intended.

**Comment by jpw1991** [comment]
Why can't you command them? It should work like in the video [here](https://youtu.be/aPN-Eobhf-s)

**Comment by Mirakakel** [comment]
They are completely ignoring me, as if i am not pressing any buttons or something.
skeleton mineres ignoring me too.
At the same time, skeleton warriors are working like in the video.

**Comment by jpw1991** [comment]
It's probably some kind of conflict. If reinstalling doesn't fix, can you please send me your log file? It will tell me what mods you're using, as well as any potential errors.

You can find it in `Valheim/BepInEx/LogOutput.log`

**Comment by Mirakakel** [comment]
> It's probably some kind of conflict. If reinstalling doesn't fix, can you please send me your log file? It will tell me what mods you're using, as well as any potential errors.
> 
> You can find it in `Valheim/BepInEx/LogOutput.log`

Reinstalled valheim, moved all other mods to diffrent folder, created new character and a new world, still something is wrong.
[LogOutput.log](https://github.com/jpw1991/chebs-necromancy/files/11800233/LogOutput.log)
Log looks fine, i suppose? no errors and other stuff.

**Comment by jpw1991** [comment]
It must be a conflict. Can you please try removing mods, one by one, until it works? I know it's tedious but we can make an educated guess about what are the most likely candidates:

1. **BetterUI** - Because this mod changes UI, maybe it changes something about the creature interactions. Try removing it and if after removing it, it works, I can contact the mod author and hopefully figure out a solution.

I can't see anything else that looks like it would conflict. So maybe try that one and let me know?

Thanks

**Comment by Mirakakel** [comment]
I have fresh installed valheim with only this mod. still something is wrong.
i changed and tweaked every thing that is possible(i think).
And it appers that problem is somewhere on my side lol.
Maybe game version? mine is 216.9
Maybe i need to level up necromancy skill to command them? upgrade skeleton staff?
I just don't know what else to do. Thanks for trying to help me, but it appers that this problem is mine and not yours.
And i see on mods thunderstore page diffrent prefered version of [ValheimModding-Jotunn](https://valheim.thunderstore.io/package/ValheimModding/Jotunn/), can that be the case?

**Comment by jpw1991** [comment]
No problem, happy to help. Feel free to ask here again if you need further help after this reply.

An outdated game version or Jotunn version could definitely be the problem. Please try updating it or using the recommended Jotunn version. There is no level restriction or anything like that when it comes to commanding the minions. If it works for the skeleton warrior, it should work the same for the woodcutter, miner, archer, etc.

There is a config option to disable commands via E on minions - but this is a broad thing and disables it on all minions. So it shouldn't be the problem in your situation - especially since it is off by default. But you can check it if you want. It's called `Commandable` and it's in the `Undead Minion` part of the config. If false, they can only be command via the wands.

**Comment by Mirakakel** [comment]
> No problem, happy to help. Feel free to ask here again if you need further help after this reply.
> 
> An outdated game version or Jotunn version could definitely be the problem. Please try updating it or using the recommended Jotunn version. There is no level restriction or anything like that when it comes to commanding the minions. If it works for the skeleton warrior, it should work the same for the woodcutter, miner, archer, etc.
> 
> There is a config option to disable commands via E on minions - but this is a broad thing and disables it on all minions. So it shouldn't be the problem in your situation - especially since it is off by default. But you can check it if you want. It's called `Commandable` and it's in the `Undead Minion` part of the config. If false, they can only be command via the wands.

I feel kinda stupid right now lol))))
although keybinds for nearby skeletons F follow and T wait are not working for woodcutters and miners, E allows me to control them at least individually, so that kinda solves the problem.
Suggestion you add E to https://github.com/jpw1991/chebs-necromancy/wiki/ControlsAndStates, because i had no clue about it))

**Comment by jpw1991** [comment]
Haha no worries. I [updated the wiki](https://github.com/jpw1991/chebs-necromancy/wiki/ControlsAndStates#activation-via-e), good suggestion.

I think it's a bug that the wand isn't working on the workers to command them. So thanks for finding that issue. I opened a new issue to track that [here](https://github.com/jpw1991/chebs-necromancy/issues/221)
