### ISSUE TITLE
Skeleton Wand Feathers One Sided - Invisible from the back

### ISSUE THREAD

**Issue by Zeinath** [jpw1991/chebs-necromancy#226]
When viewing the skeleton wand from the back (changing your view moving your mouse) the feathers on the wand disappear when viewed from the back.

## To Reproduce (if applicable)

Steps to reproduce the bug. For example:
1. Wield Skeleton Wand.
2. Spin view with mouse.
3. See disappearing act!

## Expected behavior (if applicable)

Expect all elements from the wand to be visible from all angles.

**Comment by jpw1991** [comment]
Thanks for the report. As explained in discord (for the benefit of anyone curious or reading this just now): This is because the wand uses the vanilla valheim material `GoblinStuff_mat`, which uses the `Custom/Creature` shader which is not double sided. This causes the feathers to not render when not viewed head on.

To fix, I need to change it to use a different shader. Possibly the `Standard Two Sided` shader which will render both sides, but this might affect the look of the weapon.

![image](https://github.com/jpw1991/chebs-necromancy/assets/13718599/3558b0cf-9906-4529-91b7-d5ea830c35e9)
![image](https://github.com/jpw1991/chebs-necromancy/assets/13718599/48fa6d7b-af8e-4ee7-a535-6e8c869517f1)

**Comment by jpw1991** [comment]
![image](https://github.com/jpw1991/chebs-necromancy/assets/13718599/47138467-c1ad-400b-9d60-cd2d6ebc8af8)

Fixed in next release (whenever that comes)
