### ISSUE TITLE
mod loads fine but nothing work,

### ISSUE THREAD

**Issue by zerogray1160** [jpw1991/chebs-necromancy#253]
I looked around in the forms and all known issue my issue is not present.
the mod loads correctly in. all the items appeared in game, but none of the items ability work it does not summon any zombies or skeletons, even the orb to summon skeleton Mage don't work. I can craft the item I have them and I can swing them around like melee weapons but no ability happens, so both wands and orb does not work  please help, lastly from what I've seen the mod seem amazing tyvm 

[LogOutput.log](https://github.com/jpw1991/chebs-necromancy/files/13842217/LogOutput.log)
GitHub says We don’t support that file type. cannot post config file, how else can I get it to you

**Comment by jpw1991** [comment]
Don't worry about the config. For your particular case I don't think it's useful for debugging.

You got a few different things going wrong in your log file. Some are unrelated to Cheb's Necromancy for example:

```
[Error  : Unity Log] ArgumentException: Undefined target method for patch method static System.Collections.Generic.IEnumerable<HarmonyLib.CodeInstruction> ValheimPlus.SE_Rested_GetNearbyPieces_Transpiler::Transpiler(System.Collections.Generic.IEnumerable<HarmonyLib.CodeInstruction> instructions)
```

Cheb's Necromancy doesn't appear to be installed because there is no line saying that it is loaded. For example, I'd expect to see something like `[Info   :   BepInEx] Loading [ChebsNecromancy 4.4.0]` but it is completely absent. I have no idea how any part of the mod works. You shouldn't be able to use wands, for example, as the mod isn't loaded.

## The Big Problem

However, I did notice something critical: `[Info   :   SlimVML] Loading DLLs from C:\Program Files (x86)\Steam\steamapps\common\Valheim\InSlimVML\Mods`

You're installing using Vortex right? That's a big no-no nowdays... Vortex has not been maintained for Valheim. I recommend you switch to using r2modman

**Comment by zerogray1160** [comment]
I've just started using Vortex realizing it didn't work so now I use Thunderstore App..

**Comment by zerogray1160** [comment]
the mod is currently on Thunderstore..
with what you just inform me I'm going to completely uninstall the mod and reinstall it..

**Comment by zerogray1160** [comment]
I just wanted you to know I reinstalled the mod using Thunderstore, 
same issue items appear in game fine but none of it works. the mod is installed so I don't know what to say about the issue you mentioned..is there anything else I can do tyvm..

**Comment by jpw1991** [comment]
The mod works so it must be a matter of a wrong/messed up installation. Try completely uninstalling the game so everything is fresh, then reinstall it and install r2modman. Start r2modman, make a profile, search for Cheb's Necromancy and install with dependencies.

It should all be working for you in a matter of minutes with just a few clicks.

**Comment by zerogray1160** [comment]
tyvm will do TY for all the HELP..
