### ISSUE TITLE
Mismatch on dependency version

### ISSUE THREAD

**Issue by Looneybandit** [jpw1991/chebs-necromancy#254]
Not really an issue, but got the following error when loading up my modded Valheim instance and thought it would be good to mention 

[Warning:ChebsNecromancy.BasePlugin] Patch version difference detected. The mod expects an older ChebsValheimLibrary.dll version. This probably won't cause problems.Mod expected 2.4.0, but library version is 2.4.1

**Comment by jpw1991** [comment]
Hello,

That's not an error but instead just a warning. You can ignore it. It kinda works like this:

Versioning: 1.2.3 -> major.minor.patch
major changes? definitely broken
minor? probably broken, but not necessarily
patch? just a bugfix/correction

I warn on patch version changes anyway, so that when people send me their logs I know what version of it they have. In case people say X isn't working I can say because that's patched in the next patch version. But in your case, you've got the newest version so it's all good. The warning will disappear when I next update Cheb's Necromancy
