### ISSUE TITLE
Necromancy Altar instead of Wand

### ISSUE THREAD

**Issue by RomanRomanII** [jpw1991/chebs-necromancy#81]
First of all - amazing work on this mod. It's really fun and I enjoy it a lot. 
Below are a couple of suggestions to make it more interesting. 

# Description

Vallheim is a game about crafting. You progress through finding better materials, building crafting stations, and crafting better gear. This allows you to venture further and find better materials... 
I believe to make necro more lorefull and in line with spirit of the game, it should also be crafting focused.

## Is the feature related to a problem?

The control over the type of minion spawned is lacking. I got stranded twice due to losing Surtling cores in mage summoning while trying to create an archer. 
Also, I believe minions are to easy to spam which makes the game way to easy. 

## Solutions

I propose that the process of creating minions should be done on a new crafting station - like a ritual altar.

In this crafting station you prepare remains to be reanimate:
      - you take type (skeleton, draugur, wraith, spirit), 
      - add equipment (ranged, mele, magic) 
      - and empower (0, 1 star, 2 star) 

Then create remains to be used as "ammo" with necromancer staff (which works the same as arrows for bows)

For example, you choose a skeleton, pick a bronze mele kit and empower it to level 2 - and do it 3 times. This will allow you to summon 3 mele skeletons at later date. I believe those remains should be on the heavy side, so you can't just lug around an army in your backpack. 

Creating undead type:

I think that cost to creating undead should be increased
   - 10 bone shards for skeleton, as you proposed looks fine to me
   - 10 bone shards, 3 meat, 3 intestines for draugur
   - cores for spirit type undead, with added chains for wrights

Adding equipment:

This could be done as a flat cost in resources, or which I believe is more interesting - as creating a kit at a crafting station - eg bronze sword + bronze armor + bronze helm + bronze leggings - for a bronze mele kit. 
This will make good kits more expensive and recovery will be recommended. Kits can also be a guaranteed drop from destroyed minion (add a lot of junk so it is visible - like 10 broken bone shards).

Empowering:

Using soul shards you empower a minion to chosen level. 
Soul shards could be extracted from trophies at crafting station - This will make trophies actually usefull.
   - 1 shard for animals - boar deer etc, 
   - 2 for sentient beings - skeletons, graylings etc
   - 5 from large monsters - trolls abominations, etc, 
   - 10 for bosses
 
Then you create a kit (1 shard + required materials + equipment kit) - for skeletons (2 shards for draugur)
Created kit could be upgraded to the required level using soul shards only for stronger minions.

Upgrade process will reduce clutter on the crafting station while also keeping with the spirit of the game - upgrade stations for better gear. Basic station will give you only lvl 1 undead.

Again - amazing work on the mod. It's your great mod so take from my suggestion what you like :)

**Comment by jpw1991** [comment]
Hi @RomanRomanII , thanks for your feedback and praise :)

> The control over the type of minion spawned is lacking. I got stranded twice due to losing Surtling cores in mage summoning while trying to create an archer.

Although the core issue raised by your feedback here - that control over the minion type is lacking - is absolutely true, this is relieved in the newest versions because minions return these critical and expensive components on death. So you can kill the mage and it will drop the Surtling Core.

There's too much being done by just a few buttons. A solution we have in mind is to replace these buttons with a wheel where the user can pick the minion that way.

> I think that cost to creating undead should be increased

The costs involved in creating each specific minion should hopefully soon be exposed to the config file as well. So a cheaty user could specify very low materials, or none, while a player such as yourself could specify more difficult requirements. A lot of people have a lot of different wishes regarding this point so opening it up to complete customization is, imo, the best approach.

> I propose that the process of creating minions should be done on a new crafting station - like a ritual altar.
> ...
> For example, you choose a skeleton, pick a bronze mele kit and empower it to level 2 - and do it 3 times. This will allow you to summon 3 mele skeletons at later date. I believe those remains should be on the heavy side, so you can't just lug around an army in your backpack.

I like the idea a lot. As well as the kit idea. There's two main problems though:

- **Technical** -> Skeletons and Draugr can only use one-handed swords with a specific setup or special bows with a specific setup. They can't be given player equipment. If you want them to use these things they need to be restructured to be a sword/bow with a different model. These weapons are not things the player can or should acquire. Also skeleton heads are larger than player heads, so their helmets are copies that are slightly enlarged. So either the selection of equipment is very limited, or lots of work goes into making skeleton versions of all weapons/armor.
- **My energy & existing tasks** -> There's so much to do. A big job like this is something I don't want to take on at this stage. If you really want it, the code is all here and free. Feel free to do it yourself or find a friend with the skills to do it. I don't mind.

> This will make good kits more expensive and recovery will be recommended. Kits can also be a guaranteed drop from destroyed minion (add a lot of junk so it is visible - like 10 broken bone shards).

In new versions skeletons drop their stuff inside cargo crates that float, like a destroyed boat, so it's more or less impossible to lose or miss anything they drop now.

**Comment by jpw1991** [comment]
I've created an issue https://github.com/jpw1991/chebs-necromancy/issues/82 that should address your difficulty concerns and I'm going to close the current issue as not planned. It's a very good and cool idea but I can't do it at this stage. If that ever changes, I will reopen it.

Thanks again for the feedback.

P.S. if you or anyone else want to get onboard and implement it yourselves, I encourage that and I will assist in whatever capacity I can.
